server:
  port: 8099
  # tomcat的URI编码
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 8192

spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true